(require 'ede/cpp-root)
(ede-enable-generic-projects)

(ede-cpp-root-project "common-proj"
  :name "common-proj"
  :file "~/projects/GTAGS"
  :include-path '( "/app-easy-scan/libs/sdk/ext/3dproc/include"
                   "/app-easy-scan/libs/sdk/ext/cameras/include"
                   "/app-easy-scan/libs/sdk/ext/config-enumerator/include"
                   "/app-easy-scan/libs/sdk/ext/engine/include"
                   "/app-easy-scan/libs/sdk/ext/flyuart/include"
                   "/app-easy-scan/libs/sdk/ext/tunecols/include"
                   "/app-easy-scan/libs/sdk/ext/virtualization-kit/include"
                   "/app-easy-scan/libs/sdk/ext/3drec/include"
                   "/app-easy-scan/libs/sdk/ext"
                   "/app-easy-scan/libs/sdk/algorithms/include"
                   "/app-easy-scan/libs/sdk/base/include"
                   "/app-easy-scan/libs/sdk/base/tref-sample/include"
                   "/app-easy-scan/libs/sdk/capturing/include"
                   "/app-easy-scan/libs/sdk/scanning/include"
                   "/app-easy-scan/libs/es-core/defs"
                   "/app-easy-scan/libs/rendering/a3d"
                   "/app-easy-scan/libs/rendering/"
                   "/squid-conf/include"
                   "/transport/include"
                   "/app-easy-scan/libs/callibration-manager/include"
                   "/app-easy-scan/threeparts/quazip/quazip"
                   "/app-neue-scan/libs/uncore/include"
                   "/app-astudio/astudio/source/"
                   "/app-astudio/astudio-data/include/"
                   )
  :system-include-path '( "/usr/include/qt"
                          "/usr/include"
                          "/usr/include/qt/Enginio"
                          "/usr/include/qt/Qt3DCollision"
                          "/usr/include/qt/Qt3DCore"
                          "/usr/include/qt/Qt3DInput"
                          "/usr/include/qt/Qt3DLogic"
                          "/usr/include/qt/Qt3DQuick"
                          "/usr/include/qt/Qt3DQuickRenderer"
                          "/usr/include/qt/Qt3DRenderer"
                          "/usr/include/qt/QtBluetooth"
                          "/usr/include/qt/QtCLucene"
                          "/usr/include/qt/QtConcurrent"
                          "/usr/include/qt/QtCore"
                          "/usr/include/qt/QtDBus"
                          "/usr/include/qt/QtDeclarative"
                          "/usr/include/qt/QtDesigner"
                          "/usr/include/qt/QtDesignerComponents"
                          "/usr/include/qt/QtGui"
                          "/usr/include/qt/QtHelp"
                          "/usr/include/qt/QtLocation"
                          "/usr/include/qt/QtMultimedia"
                          "/usr/include/qt/QtMultimediaQuick_p"
                          "/usr/include/qt/QtMultimediaWidgets"
                          "/usr/include/qt/QtNetwork"
                          "/usr/include/qt/QtNfc"
                          "/usr/include/qt/QtOpenGL"
                          "/usr/include/qt/QtOpenGLExtensions"
                          "/usr/include/qt/QtPlatformHeaders"
                          "/usr/include/qt/QtPlatformSupport"
                          "/usr/include/qt/QtPositioning"
                          "/usr/include/qt/QtPrintSupport"
                          "/usr/include/qt/QtQml"
                          "/usr/include/qt/QtQmlDevTools"
                          "/usr/include/qt/QtQuick"
                          "/usr/include/qt/QtQuickParticles"
                          "/usr/include/qt/QtQuickTest"
                          "/usr/include/qt/QtQuickWidgets"
                          "/usr/include/qt/QtScript"
                          "/usr/include/qt/QtScriptTools"
                          "/usr/include/qt/QtSensors"
                          "/usr/include/qt/QtSerialPort"
                          "/usr/include/qt/QtSql"
                          "/usr/include/qt/QtSvg"
                          "/usr/include/qt/QtTest"
                          "/usr/include/qt/QtUiPlugin"
                          "/usr/include/qt/QtUiTools"
                          "/usr/include/qt/QtWaylandClient"
                          "/usr/include/qt/QtWebChannel"
                          "/usr/include/qt/QtWebEngine"
                          "/usr/include/qt/QtWebEngineWidgets"
                          "/usr/include/qt/QtWebKit"
                          "/usr/include/qt/QtWebKitWidgets"
                          "/usr/include/qt/QtWebSockets"
                          "/usr/include/qt/QtWidgets"
                          "/usr/include/qt/QtX11Extras"
                          "/usr/include/qt/QtXml"
                          "/usr/include/qt/QtXmlPatterns"
                          "/usr/include/qt/"
                          "/usr/include/wx-2.8"
                          "/usr/lib/wx/include/gtk2-unicode-release-2.8"
                          )
  )

(provide 'my-ede-project)
