(deftheme px-dichromacy
  "Created 2015-09-29.")

(custom-theme-set-faces
 'px-dichromacy
 '(cursor ((((background light)) (:background "black")) (((background dark)) (:background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#d55e00"))))
 '(minibuffer-prompt ((t (:foreground "#0072b2"))))
 '(highlight ((t (:foreground "#0072b2" :background "#e5e5e5"))))
 '(region ((t (:background "#f8ec59"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#e5e5e5"))))
 '(trailing-whitespace ((t (:background "#d55e00"))))
 '(font-lock-builtin-face ((t (:foreground "#0072b2"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :height 0.94))))
 '(font-lock-comment-face ((t (:foreground "light sky blue" :slant oblique))))
 '(font-lock-constant-face ((t (:foreground "#d55e00" :weight normal))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#d55e00"))))
 '(font-lock-keyword-face ((t (:foreground "DodgerBlue3" :weight semi-light))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#848ea9"))))
 '(font-lock-type-face ((t (:weight bold :foreground "#0072b2"))))
 '(font-lock-variable-name-face ((t (:foreground "#e69f00" :weight semi-light))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#0072b2"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#cc79a7"))))
 '(fringe ((t (:background "white"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:background "gray96" :foreground "black"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:family "monofur"))))
 '(mode-line-inactive ((t (:background "gray96" :foreground "gray24"))))
 '(isearch ((t (:foreground "white" :background "#d55e00"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "white" :background "#cc79a7"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :stipple nil :background "white" :foreground "gray10" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 128 :width normal :foundry "unknown" :family "monofur"))))
 '(header-line ((t (:inherit mode-line :background "grey96" :foreground "grey40" :box nil :height 0.8)))))

(provide-theme 'px-dichromacy)
